---
title: "Venn_Diagram"
author: "Bryan Rodriguez"
date: "2025-06-03"
output: html_document
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

setwd("/Users/bryanrodriguez/Library/CloudStorage/OneDrive-UniversityofKansas/Bryan-MS_PhD/PHD-PROJECT/PuertoRico/CHAPTER2/16S/Processing/Geobio_Guanica_Codes/R_Codes")
rm(list = ls())


```



```{r Load packages}

library(VennDiagram)
library(ggvenn)
library(phyloseq)     # For microbiome data structures and manipulation
library(data.table)   # For efficient data handling
library(dplyr)        # For data manipulation (e.g., group_by, summarize)
library(ggplot2)

```



```{r Load data}
melt_file_list <- readRDS("OutputData/RData/PE_GuanicaGeobio_Arch_Bac_merged_rel_melt_SLayer.RDS")


Arch_Bac_merged_rel_melt <- melt_file_list$Arch_Bac_merged_rel_melt_SLayer
Arch_merged_rel_melt <- melt_file_list$Arch_merged_rel_melt_SLayer
Bac_merged_rel_melt <- melt_file_list$Arch_Bac_merged_rel_melt_SLayer

rm(melt_file_list)
```



## Splitting Data by sample
Splitting Data by Sample_name summarizing abundance data at each taxonomic level and sorting abundance in descending order. 
```{r split data by sample layer}
Arch_merged_rel_melt_group <- Arch_merged_rel_melt %>% dplyr::group_by(Sample_name, OTU, Phylum, Class, Order, Family, Genus) %>% dplyr::summarize(Rel_Abund = sum(RelAbund), Rel_Abund_SD = sd(RelAbund)) %>% arrange(desc(Rel_Abund))

Bac_merged_rel_melt_group <- Bac_merged_rel_melt %>% dplyr::group_by(Sample_name, OTU, Phylum, Class, Order, Family, Genus) %>% dplyr::summarize(Rel_Abund = sum(RelAbund), Rel_Abund_SD = sd(RelAbund)) %>% arrange(desc(Rel_Abund))

Arch_Bac_merged_rel_melt_group <- Arch_Bac_merged_rel_melt %>% dplyr::group_by(Sample_name, OTU, Phylum, Class, Order, Family, Genus) %>% dplyr::summarize(Rel_Abund = sum(RelAbund), Rel_Abund_SD = sd(RelAbund)) %>% arrange(desc(Rel_Abund))

rm(Arch_merged_rel_melt, Bac_merged_rel_melt, Arch_Bac_merged_rel_melt)

```



# Filter by name


```{r Filter by name}
# Filter by lagoon and extract unique Genus
OTU_PO <- Arch_Bac_merged_rel_melt_group %>%
  filter(Sample_name == "POE1", Rel_Abund > 0, !is.na(OTU)) %>%
  pull(OTU) %>%
  unique()

OTU_JB <- Arch_Bac_merged_rel_melt_group %>%
  filter(Sample_name == "JB", Rel_Abund > 0, !is.na(OTU)) %>%
  pull(OTU) %>%
  unique()

OTU_PS <- Arch_Bac_merged_rel_melt_group %>%
  filter(Sample_name == "PS", Rel_Abund > 0, !is.na(OTU)) %>%
  pull(OTU) %>%
  unique()


```

## Plot Venn Diagram

```{r Plot}

Genus_list <- list(PO = Gen_PO, JB = Gen_JB, PS = Gen_PS)

venn_plot <- ggvenn(Genus_list, 
       fill_color = c("blue", "red", "green"), 
       text_size = 3, 
       set_name_size = 4)


ggsave(
  filename = "plots/Statistics/venn_plot_PerSample.tiff",
  plot = venn_plot,
  width = 6,
  height = 6
)



```




